config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get '/hello', to: 'greeter#hello'
  get '/goodbye', to: 'greeter#goodbye'

  root to: 'courses#index'

end

app/models/coursera.rb
class Coursera
  include HTTParty

  base_uri 'https://api.coursera.org/api/catalog.v1/courses'
  default_params fields: "smallIcon,shortDescription", q: "search"
  format :json

  def self.for term
    get("", query: { query: term})["elements"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @search_term = params[:looking_for] || 'jhu'
    @courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    randon_names = ["Alex", "Joe", "Sam"]
    @name = randon_names.sample
    @time = Time.now
    @times_displayed ||= 0
    @times_displayed += 1
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
  def formated_time(time)
    # time in AM/PM format
    time.strftime("%I:%M%p")
  end
end

app/views/courses/index.html.erb
<h1>Searching for - <%= @search_term %> </h1>


<%= form_tag("/", method: "get") do %>
  <%= label_tag(:looking_for, "Search for: ") %>
  <%= text_field_tag(:looking_for) %>
  <%= submit_tag("Search") %>
<% end %>

<br><br>
<% if @courses.nil? %>
  <h2>No courses found for <em>'<%= @search_term %>'</em></h2>
  <button type="button" name="button">
    <%= link_to "<<< Back to Index", root_path %>
  </button>
<% else %>
  <table border="1">
    <tr>
      <th>
        Image
      </th>
      <th>
        Name
      </th>
      <th>
        Description
      </th>
    </tr>
    <% @courses.each do |course| %>
      <tr class=<%= cycle('even', 'odd') %>>
        <td>
          <%= image_tag(course["smallIcon"]) %>
        </td>
        <td>
          <%= course["name"] %>
        </td>
        <td>
          <%= course["shortDescription"] %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/greeter/goodbye.html.erb
<% randon_names = ["Alex", "Joe", "Sam"] %>
<h1>Good bye, <%= randon_names.sample %></h1>
<p>
  The time now is <%= Time.now %>
</p>

<%= link_to "Hello", hello_path %>

app/views/greeter/hello.html.erb
<h1>Greetings, <%= @name %></h1>
<p>
  The time now is <%= formated_time(@time) %>
</p>
<p>
  <%= @times_displayed %> times displayed.
</p>

<%= link_to "Good bye", goodbye_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>